### ISSUE TITLE
Change status 

### ISSUE THREAD

**Issue by giren7384** [Hot-Tutorials/Dark-Sorus#1]
![Screenshot (147)](https://user-images.githubusercontent.com/69572254/106328167-56036900-624d-11eb-9e4b-8cc80df11ca2.png)
Status font stuff is absolutely massive not sure if you meant for it to be like that but you cant see the icons too

**Comment by LynithDev** [comment]
Oh no not this again. I thought I fixed it yesterday and pushed it. Weird. This is most likely to do with discord updating and renaming the id of the popup. Thanks for letting me know I will change this tmrw when I wake up
